version: '3.1'

services:

  db:
    image: postgres:11
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: 123test
      POSTGRES_USER: test
      POSTGRES_DB: lovelystay_test
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080